name: SALINES
favicon: null
layout_spectrum: 0.10367854754440486
typography_spectrum: 0.2656609758269042
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e5d7d6'
    - '#082d25'
    - '#a07b69'
    - '#37dbda'
    - '#01a45a'
  brandStrength: 0.7975102127529681
  lightness: 0.009092767257243395
  saturation: 0.9134118263609707
  rhythmicContrast: 0.7193781619425863
purpose: []
