name: SALINES
favicon: null
layout_spectrum: 0.24532
typography_spectrum: 0.2656609758269042
title: THE SALT EXPERIENCE    SALINES
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#bac7b6'
    - '#1865bd'
    - '#5e3502'
    - '#0ab4ad'
    - '#fefef9'
  brandStrength: 0
  lightness: 0.75
  saturation: 0.9134118263609707
  rhythmicContrast: 0.7193781619425863
purpose: []
